### ISSUE TITLE
Do not shrink image when call bimg.Crop

### ISSUE THREAD

**Issue by fikgol** [h2non/bimg#172]

**Comment by greut** [comment]
What did you do and what didn't go as expected?

**Comment by valerykalashnikov** [comment]
original image:
![image](https://user-images.githubusercontent.com/1069061/29576669-5e3455fe-8771-11e7-8a4c-869d71ec0876.png)

when doing
```
newImage, err := image.CropByWidth(300)
```
cropped  image looks like this:
![new_crop_by_width](https://user-images.githubusercontent.com/1069061/29576743-a53e47e8-8771-11e7-8e83-8c658a0c74a1.png)
It possible to read text on this image, because it is large.

when doing
```
newImage, err := image.Crop(300, 300, bimg.GravityCentre)
```
cropped image looks like this:
![new_crop](https://user-images.githubusercontent.com/1069061/29576837-04186dc0-8772-11e7-8035-b8a00add213d.png)

It is impossible to recognize any symbol because they are too small.

I think @fikgol waits such result(cropped by image editor)
![expected_image](https://user-images.githubusercontent.com/1069061/29577070-cc33f5e0-8772-11e7-896d-3ffcb2e3c6dc.png)
