### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by hgl** [h2non/bimg#209]
I'm playing with this package, and it's quite impressive. But I have one quick question: from the API, it seems it tries to read the whole image into memory and then do the processing, but it seems [libvips is able to work one area at a time](https://github.com/lovell/sharp/issues/30#issuecomment-43967447) when it woks with a file.

Is such capability exposed by this package?

I'm trying to write a image processing rest api, and am worried that by reading the whole image into memory it could lead to high memory usage when there are many concurrent requests.

**Comment by hgl** [comment]
Or it's deliberately loaded into memory to process faster?

**Comment by greut** [comment]
The use case is [imaginary](https://github.com/h2non/imaginary) which works with data _in-memory_. It might explain the choices made when building _bimg_.

**Comment by h2non** [comment]
Yes, that's right. This was intentional by design for several reasons, but perhaps the obvious one is because of FFI between Go and C make things considerably easier and more versatile by just passing a pointer to memory, especially in terms of error management and `cgo` bridge. 

While working with disk I/O [is possible in libvips](http://jcupitt.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-file), it would force persisting things into disk, which is not always desirable. That being said, I'm not close to explore supporting different image loading strategies in the future.

**Comment by hgl** [comment]
Makes sense.

Right now I just exec the CLI . If working with disk I/O turns out to be sub-optimal, I'll switch back to bimg.

 Thanks guys.
