### ISSUE TITLE
Error while building bimg.v1 for go1.8

### ISSUE THREAD

**Issue by palaiya** [h2non/bimg#244]
I am getting the following error while building `bimg.v1` for `go version go1.8 linux/amd64`. 

```
Fetching https://gopkg.in/h2non/bimg.v1?go-get=1
Parsing meta tags from https://gopkg.in/h2non/bimg.v1?go-get=1 (status code 200)
get "gopkg.in/h2non/bimg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/h2non/bimg.v1", VCS:"git", RepoRoot:"https://gopkg.in/h2non/bimg.v1"} at https://gopkg.in/h2non/bimg.v1?go-get=1
gopkg.in/h2non/bimg.v1 (download)
gopkg.in/h2non/bimg.v1
# gopkg.in/h2non/bimg.v1
In file included from ../../softwares/src/gopkg.in/h2non/bimg.v1/vips.go:5:0:
./vips.h:180:1: error: conflicting types for 'vips_rotate'
 vips_rotate(VipsImage *in, VipsImage **out, int angle) {
 ^
In file included from /usr/local/include/vips/vips.h:145:0,
                 from ./vips.h:3,
                 from ../../softwares/src/gopkg.in/h2non/bimg.v1/vips.go:5:
/usr/local/include/vips/resample.h:85:5: note: previous declaration of 'vips_rotate' was here
 int vips_rotate( VipsImage *in, VipsImage **out, double angle, ... )
     ^
```
Though i also tried to build `bimg.v0`. It prompts for the username and password and then says 

`remote: Repository not found.
fatal: repository 'https://github.com/tj/go-debug/' not found
package github.com/tj/go-debug: exit status 128
`

**Comment by mickael-kerjean** [comment]
Same here, did you find a solution?

**Comment by krak3n** [comment]
Looks like `vips_rotate` was added 5 months ago in `v8.7.0` of `libvips`: https://github.com/jcupitt/libvips/blame/3b1e3e1841dab816dcf9550bde857423fb57b77f/libvips/include/vips/resample.h#L85 If you are building `libvips` from master or from a an AUR (on Arch platforms) like me (from here https://aur.archlinux.org/packages/libvips-git/ - I got `libvips-git 8.7.0.rc1.r5.gc1dcb0c5-1 (Fri 10 Aug 2018 11:38:04 BST)`) you'll get the latest which includes the change causing the compilation problem.

As a short term fix I guess you'll need to install `v8.6.x` which does not include the change. That makes sense at the moment since `v8.7.x` is a release candidate. Once it is released however I think this project will need to make some changes to avoid the duplicate deceleration of `vips_rotate`.

**Comment by ewawrzas** [comment]
I'm having the same issue - is there a long term fix in place for this?

**Comment by Dynom** [comment]
@ewawrzas is it possible for you to build in a Docker container?

**Comment by sameeakhan** [comment]
@Dynom it is not possible for me to build in a Docker container. Seeing this issue in libvips v8.8.0 and v8.7.x as well. Can only successfully build up to v8.6.5.

**Comment by h2non** [comment]
Deprecated. Please use `libvips@8.8+` and `bimg@1.1+`.
