### ISSUE TITLE
Finetune option types

### ISSUE THREAD

**Issue by christopheeble** [h2non/bimg#37]
I think using `uint` type for options such as `Width`, `Height`, `Quality` and `Compression` would be more appropriate, it's very uncommon to use unsigned integers for this kind of stuff :)

https://github.com/h2non/bimg/blob/master/options.go#L75

**Comment by h2non** [comment]
Absolutely, but I'd prefer using the `int` type just because it's the default type inferred in Go. 
If I change it to `int8`, it requires explicit type definition, generating too much boilerplate. 
See this [example](http://play.golang.org/p/kMmb1_YwWe)

By the other hand, I can't change this for now due to it will break the existent public interface contract.

Also, libvips C API mostly uses `int` types, so I could make a type casting to `int8` internally (which doesn't compromise the public API), but CGO will cast it again into `int` when generating intermediate code for FFI with C code.

Conclusion: nothing significant to win.
