### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by chreble** [h2non/bimg#41]
Currently GIF images are detected with the `magick` code but fails the `IsTypeSupported` check in `type.go` package. Is there any blocker to support GIF (via libvips)?

I know you can process GIFs using libvips but only if you configure it with libMagick support, maybe it's the culprit.

**Comment by chreble** [comment]
@h2non I see that you added preliminary support in https://github.com/h2non/bimg/commit/7be9d7bad55ebd12fbaa482314c5bd7b41ff5fec, cool!

**Comment by h2non** [comment]
You're right. GIF image formats (and SVG, TIFF... as well) can be handled by libvips, if it's backed by `libmagick`. 

Since `libmagick` is an standalone library which is not provided by default with `libvips`, I've no plans to provide any specific support to it bundled with `bimg`, except detecting the `magick` generic type as you've mentioned, in order to handle that type accordingly if your `libvips` environment can deal new types via third-party integrations.

At the moment I don't need to handle GIF based images, but if you are looking for that, feel free to fork and make the hacks you need. I'm curious about seeing it handling new images formats (specially SVG) in a reliable way.

**Comment by chonthu** [comment]
I been playing with gifsicle (recommended my google in pagespeed docs), for now I just detect type of image == gif and run it through a simple wrapper like this https://github.com/chonthu/gifopt.

**Comment by foresmac** [comment]
FWIW, if you build from github master, you get non-imagemagick GIF loading: http://libvips.blogspot.com/2016/02/new-image-loaders.html

Looks like it will be officially supported in 8.3.

**Comment by h2non** [comment]
GIF, SVG and PDF image processing is finally available in latest versions of bimg/imaginary.

**Comment by timendez** [comment]
@h2non Are there any plans to allow for animated gif output?

**Comment by t101804** [comment]
> @h2non Are there any plans to allow for animated gif output?

is there already allow for animated gif output?
