### ISSUE TITLE
Cropping behavior not working?

### ISSUE THREAD

**Issue by cneerdaels** [h2non/bimg#62]
After running the tests, if you visually compare test_crop_height_out.jpg, test_crop_width_out.jpg, and test.jpg - it appears like the output dimensions are correct, but there's no actual cropping. It seems more like a forced resize.

**Comment by h2non** [comment]
The crop behavior is correct. Those tests images uses the crop by weight or height only, which means the resolution image will remain the aspect ratio, so there's not crop perse operation required, just a resize one. Indeed, the `CropByWidth` and `CropByHeight` method are wrong and incongruent.

To perform a proper crop operation you should pass width and height params.
I would consider printing a warning message when use those methods since.
